'use client';

import React, { useMemo, useState } from 'react';
import Link from 'next/link';
import { AnimatePresence, motion } from 'framer-motion';
import clsx from 'clsx';
import { INDUSTRIES } from '@/lib/industries';
import { demoRespond, INITIAL_DEMO_STATE } from '@/lib/demo-agent';
import { SectionHeading } from '@/components/ui/motion';
import { Icon } from '@/components/ui/Icons';

export function Industries() {
  const [id, setId] = useState(INDUSTRIES[2].id);
  const ind = INDUSTRIES.find((i) => i.id === id)!;
  // Sample exchange generated by the same engine that powers the demo.
  const sample = useMemo(() => {
    const q = ind.demo.prompts[0];
    return { q, a: demoRespond(ind, INITIAL_DEMO_STATE, q).reply };
  }, [ind]);

  return (
    <section className="relative bg-white py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <SectionHeading
          eyebrow="Beauty, clinics — and beyond"
          title={<>Built for every business <span className="text-purple-gold">that runs on bookings.</span></>}
          subtitle="Trained on the language of your industry, with the right safety rules for it. Pick yours."
        />

        <div className="mt-14 grid grid-cols-1 gap-6 lg:grid-cols-[0.8fr_1.2fr] [&>*]:min-w-0">
          <div className="no-scrollbar -mx-4 flex gap-2 overflow-x-auto px-4 lg:mx-0 lg:grid lg:grid-cols-2 lg:gap-3 lg:overflow-visible lg:px-0">
            {INDUSTRIES.map((i) => (
              <button
                key={i.id}
                onClick={() => setId(i.id)}
                className={clsx(
                  'group flex shrink-0 items-center gap-3 rounded-2xl border px-4 py-3.5 text-left transition-all lg:py-5',
                  i.id === id
                    ? 'border-brand-purple bg-brand-purple text-white shadow-[0_20px_40px_-15px_rgba(109,40,217,0.6)]'
                    : 'border-brand-purple/10 bg-brand-light/60 text-brand-black hover:border-brand-purple/30 hover:bg-white'
                )}
              >
                <span className={clsx('flex h-9 w-9 shrink-0 items-center justify-center rounded-xl transition-colors', i.id === id ? 'bg-white/15 text-brand-gold' : 'bg-white text-brand-purple')}>
                  <Icon name={i.icon} className="h-[18px] w-[18px]" />
                </span>
                <span className="whitespace-nowrap text-sm font-semibold">{i.name}</span>
              </button>
            ))}
            <Link href="/waitlist" className="flex shrink-0 items-center gap-3 rounded-2xl border border-dashed border-brand-gold/60 px-4 py-3.5 text-sm font-semibold text-brand-black transition-colors hover:bg-brand-cream lg:col-span-2 lg:justify-center lg:py-5">
              <Icon name="grid" className="h-[18px] w-[18px] text-brand-gold" />
              Something else? If you take bookings, it works.
            </Link>
          </div>

          <AnimatePresence mode="wait">
            <motion.div
              key={ind.id}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -16 }}
              transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
              className="relative overflow-hidden rounded-[2rem] bg-[#0C0A1D] p-6 text-white sm:p-9"
            >
              <div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-brand-purple/40 blur-3xl" />
              <div className="relative">
                <div className="flex items-center gap-3">
                  <span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-brand-gold text-brand-black">
                    <Icon name={ind.icon} className="h-6 w-6" />
                  </span>
                  <div>
                    <h3 className="font-display text-2xl font-bold text-white">{ind.name}</h3>
                    <p className="text-sm text-white/55">{ind.tagline}</p>
                  </div>
                </div>

                <div className="mt-8 grid gap-4 sm:grid-cols-2">
                  <div className="rounded-2xl border border-rose-400/15 bg-rose-400/[0.05] p-5">
                    <p className="mb-3 text-[11px] font-bold uppercase tracking-[0.18em] text-rose-300/80">Without Resevia</p>
                    <ul className="space-y-2.5">
                      {ind.pains.map((p) => (
                        <li key={p} className="flex gap-2.5 text-sm text-white/70"><Icon name="x" className="mt-0.5 h-4 w-4 shrink-0 text-rose-400" />{p}</li>
                      ))}
                    </ul>
                  </div>
                  <div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/[0.05] p-5">
                    <p className="mb-3 text-[11px] font-bold uppercase tracking-[0.18em] text-emerald-300/80">With Resevia</p>
                    <ul className="space-y-2.5">
                      {ind.wins.map((w) => (
                        <li key={w} className="flex gap-2.5 text-sm text-white/85"><Icon name="check" className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400" />{w}</li>
                      ))}
                    </ul>
                  </div>
                </div>

                <div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.03] p-5">
                  <p className="mb-3 text-[11px] font-bold uppercase tracking-[0.18em] text-white/40">Sample conversation · {ind.demo.business}</p>
                  <div className="space-y-2">
                    <div className="ml-auto w-fit max-w-[85%] rounded-2xl rounded-br-md bg-white/10 px-3.5 py-2 text-sm">{sample.q}</div>
                    <div className="w-fit max-w-[90%] whitespace-pre-line rounded-2xl rounded-bl-md border border-brand-gold/25 bg-brand-gold/10 px-3.5 py-2 text-sm">
                      <span className="mb-0.5 block text-[10px] font-semibold uppercase tracking-wider text-brand-gold">{ind.demo.agent}</span>
                      {sample.a}
                    </div>
                  </div>
                </div>

                <Link href="#demo" className="group mt-6 inline-flex items-center gap-2 text-sm font-semibold text-brand-gold">
                  Continue this conversation in the live demo
                  <Icon name="arrowRight" className="h-4 w-4 transition-transform group-hover:translate-x-1" />
                </Link>
              </div>
            </motion.div>
          </AnimatePresence>
        </div>
      </div>
    </section>
  );
}
